<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="custom" nsURI="http://org/eclipse/emf/ecp/view/custom/model"
    nsPrefix="org.eclipse.emf.ecp.view.custom.model">
  <eClassifiers xsi:type="ecore:EClass" name="CustomControl" eSuperTypes="../../org.eclipse.emf.ecp.view.model/model/view.ecore#//Control">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bundleName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomDomainModelReference" eSuperTypes="../../org.eclipse.emf.ecp.view.model/model/view.ecore#//DomainModelReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainModelReferences"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.emf.ecp.view.model/model/view.ecore#//DomainModelReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bundleName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlChecked" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" transient="true"
        defaultValueLiteral="false"/>
  </eClassifiers>
</ecore:EPackage>
