<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="multisegment" nsURI="http://org/eclipse/emfforms/view/multisegment/model/1190"
    nsPrefix="org.eclipse.emfforms.view.multisegment.model">
  <eClassifiers xsi:type="ecore:EClass" name="MultiDomainModelReferenceSegment" eSuperTypes="../../org.eclipse.emf.ecp.view.model/model/view.ecore#//FeatureDomainModelReferenceSegment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childDomainModelReferences"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.emf.ecp.view.model/model/view.ecore#//DomainModelReference"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
