<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="domainmodelreference" nsURI="http://www.eclipse.org/emf/ecp/view/template/selector/domainmodelreference/model"
    nsPrefix="org.eclipse.emf.ecp.view.template.selector.domainmodelreference.model">
  <eClassifiers xsi:type="ecore:EClass" name="DomainModelReferenceSelector" eSuperTypes="template.ecore#//StyleSelector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainModelReference" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecp.view.model/model/view.ecore#//DomainModelReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootEClass" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The root EClass of the selector's domain model reference. The selector's DMR is resolved against this EClass."/>
        <details key="propertyDescription" value="The root EClass of the selector's domain model reference. The reference is resolved against this EClass."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
