<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="domainmodelreference" nsURI="http://www.eclipse.org/emf/ecp/view/template/selector/domainmodelreference/model"
    nsPrefix="org.eclipse.emf.ecp.view.template.selector.domainmodelreference.model">
  <eClassifiers xsi:type="ecore:EClass" name="DomainModelReferenceSelector" eSuperTypes="template.ecore#//StyleSelector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainModelReference" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecp.view.model/model/view.ecore#//DomainModelReference"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
