<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tableValidation" nsURI="http://www.eclipse.org/emf/ecp/view/template/style/table/validation/model"
    nsPrefix="org.eclipse.emf.ecp.view.template.style.table.validation.model">
  <eClassifiers xsi:type="ecore:EClass" name="TableValidationStyleProperty" eSuperTypes="template.ecore#//StyleProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imagePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
