<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tableStyleProperty" nsURI="http://www.eclipse.org/emf/ecp/view/template/style/table/model"
    nsPrefix="org.eclipse.emf.ecp.view.template.style.table.model">
  <eClassifiers xsi:type="ecore:EClass" name="TableStyleProperty" eSuperTypes="template.ecore#//StyleProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showValidationSummaryTooltip"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enableSorting" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibleLines" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="renderMode" eType="#//RenderMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RenderMode">
    <eLiterals name="DEFAULT" literal="DEFAULT"/>
    <eLiterals name="COMPACT_VERTICALLY" value="1" literal="COMPACT_VERTICALLY"/>
  </eClassifiers>
</ecore:EPackage>
