<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bpackage" nsURI="b.nsuri" nsPrefix="bprefix">
  <eClassifiers xsi:type="ecore:EClass" name="bclass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="b1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="b2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b3" eType="ecore:EClass A.ecore#//aclass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="b4" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
</ecore:EPackage>
