<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="indexdmr" nsURI="http://www.eclipse.org/emf/ecp/view/indexdmr/model"
    nsPrefix="org.eclipse.emf.ecp.view.indexdmr.model">
  <eClassifiers xsi:type="ecore:EClass" name="IndexDomainModelReference" eSuperTypes="../../org.eclipse.emf.ecp.view.model/model/view.ecore#//FeaturePathDomainModelReference">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="resolveable"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prefixDMR" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecp.view.model/model/view.ecore#//DomainModelReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetDMR" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecp.view.model/model/view.ecore#//DomainModelReference"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
