<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="e" nsURI="http://example.org/e" nsPrefix="e">
  <eClassifiers xsi:type="ecore:EClass" name="E">
    <eStructuralFeatures xsi:type="ecore:EReference" name="d" eType="ecore:EClass d.ecore#//D"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="f" eType="ecore:EClass f.ecore#//F"/>
  </eClassifiers>
</ecore:EPackage>
