<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="y" nsURI="http://example.org/y" nsPrefix="y">
  <eClassifiers xsi:type="ecore:EClass" name="Y">
    <eStructuralFeatures xsi:type="ecore:EReference" name="x" eType="ecore:EClass x.ecore#//X"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="z" eType="ecore:EClass z.ecore#//Z"/>
  </eClassifiers>
</ecore:EPackage>
