<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stack" nsURI="http://org/eclipse/emf/ecp/view/stack/model" nsPrefix="org.eclipse.emf.ecp.view.stack.model">
  <eClassifiers xsi:type="ecore:EClass" name="StackLayout" eSuperTypes="../../org.eclipse.emf.ecp.view.model/model/view.ecore#//ContainedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainModelReference" eType="ecore:EClass ../../org.eclipse.emf.ecp.view.model/model/view.ecore#//DomainModelReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stackItems" upperBound="-1"
        eType="#//StackItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topElement" eType="#//StackItem"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StackItem" eSuperTypes="../../org.eclipse.emf.ecp.view.model/model/view.ecore#//Container">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
</ecore:EPackage>
