<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="section" nsURI="http://org/eclipse/emf/ecp/view/section/model"
    nsPrefix="org.eclipse.emf.ecp.view.section.model">
  <eClassifiers xsi:type="ecore:EClass" name="SectionedArea" eSuperTypes="../../org.eclipse.emf.ecp.view.model/model/view.ecore#//ContainedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="#//Section"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section" eSuperTypes="../../org.eclipse.emf.ecp.view.model/model/view.ecore#//Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childItems" upperBound="-1"
        eType="#//Section" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collapsed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
</ecore:EPackage>
