<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="compoundcontrol" nsURI="http://org/eclipse/emf/ecp/view/compoundcontrol/model"
    nsPrefix="org.eclipse.emf.ecp.view.compoundcontrol.model">
  <eClassifiers xsi:type="ecore:EClass" name="CompoundControl" eSuperTypes="../../org.eclipse.emf.ecp.view.model/model/view.ecore#//Control">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.emf.ecp.view.model/model/view.ecore#//Control"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
